name: modifier
description: Syntax sugar optimizations to avoid nesting hell in Flutter.
version: 0.1.0
homepage: https://github.com/treeinfra/modifier
environment: {sdk: ">=3.4.3 <4.0.0", flutter: ">=3.22.2"}
topics:
  - cascade
  - code-style
  - modifier
  - nesting-hell
  - syntax-sugar

dependencies:
  flutter: {sdk: flutter}

dev_dependencies:
  flutter_test: {sdk: flutter}
  lintall: ^0.1.0
