name: modifier_example_after
description: An example after using the modifier package.
publish_to: "none"
version: 0.0.0
environment: {sdk: ">=3.4.3 <4.0.0"}

dependencies:
  flutter: {sdk: flutter}
  modifier: {path: ../../}

dev_dependencies:
  flutter_test: {sdk: flutter}
  lintall: ^0.1.1
