name: common
description: Example for theme and locale using the modifier package.
publish_to: "none"
version: 0.0.0 # The version code will always be zero.
environment: {sdk: ">=3.4.3 <4.0.0"}

dependencies:
  cupertino_icons: ^1.0.6
  flutter: {sdk: flutter}

dev_dependencies:
  flutter_test: {sdk: flutter}
  lintall: ^0.1.1

flutter:
  uses-material-design: true
